version: 1.0.{build}
build:
  verbosity: minimal
artifacts:
- path: App2\AppPackages
  name: App2
  type: zip
deploy_script:
- ps: >-
    $fileBin = [IO.File]::ReadAllBytes($artifacts["App2"].path)

    $enc = [System.Text.Encoding]::GetEncoding("iso-8859-1")

    $fileEnc = $enc.GetString($fileBin)


    $boundary = [System.Guid]::NewGuid().ToString()

    $LF = "`n"

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"

    $headers.Add("X-HockeyAppToken", "9e1f829fc8ec4ad3a6fe1f289635068a")

    $body = @{status='2';ipa=$fileEnc}

    Invoke-RestMethod https://rink.hockeyapp.net/api/2/apps/00b9b42e03c2f787077bd5d13ccf146d/app_versions
    -Method Post
    -ContentType "multipart/form-data; boundary=`"$boundary`""
    -Body $body -Headers $headers
