version: 1.0.{build}
build:
  verbosity: minimal
artifacts:
- path: App2\AppPackages
  name: App2
  type: zip
deploy_script:
- ps: >-
    . ".\scripts\build-config.ps1"

    . ".\scripts\deploy-script.ps1"
