version: 1.0.{build}
build:
  verbosity: minimal
artifacts:
- path: App2\AppPackages
  name: App2
  type: zip
deploy_script:
- ps: >-
    $fileBin = [IO.File]::ReadAllBytes($artifacts["App2"].path)

    $enc = [System.Text.Encoding]::GetEncoding("iso-8859-1")

    $fileEnc = $enc.GetString($fileBin)


    $boundary = [System.Guid]::NewGuid().ToString()

    $LF = "`r`n"

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"

    $headers.Add("X-HockeyAppToken", "9e1f829fc8ec4ad3a6fe1f289635068a")

    $bodyLines = (
        "--$boundary",
        "Content-Disposition: form-data; name=`"ipa`"; filename=`"$artifacts[`"App2`"].path`"",
        "Content-Type: application/octet-stream$LF",
        $fileEnc,
        "--$boundary",
        "Content-Disposition: form-data: name=`"status`"$LF",
        "2",
        "--$boundary",
        "Content-Disposition: form-data: name=`"notify`"$LF",
        "0",
        "--$boundary",
        "Content-Disposition: form-data: name=`"notes`"$LF",
        "",
        "--$boundary",
        "Content-Disposition: form-data: name=`"notes_type`"$LF",
        "0",
        "--$boundary--$LF"
    ) -join $LF

    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

    $response = Invoke-RestMethod https://rink.hockeyapp.net/api/2/apps/00b9b42e03c2f787077bd5d13ccf146d/app_versions/new
    -Method Post
    -Body "bundle_version=3"
    -Headers $headers

    $id = $response.id

    Invoke-RestMethod https://rink.hockeyapp.net/api/2/apps/00b9b42e03c2f787077bd5d13ccf146d/app_versions/$id
    -Method Put
    -ContentType "multipart/form-data; boundary=`"$boundary`""
    -Body $bodyLines
    -Headers $headers
