version: 1.0.{build}
build:
  verbosity: minimal
artifacts:
- path: App2\AppPackages
  name: App2
  type: zip
deploy_script:
- ps: >-
    $fileBin = [IO.File]::ReadAllBytes($artifacts["App2"].path)

    Write-Host $artifacts["App2"]

    Write-Host $artifacts["App2"].path

    Write-Host $artifacts["App2"].url

    $enc = [System.Text.Encoding]::GetEncoding("iso-8859-1")

    $fileEnc = $enc.GetString($fileBin)


    $boundary = [System.Guid]::NewGuid().ToString()

    $LF = "`n"

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"

    $headers.Add("X-HockeyAppToken", "4fa71bd6299744759e2d5ac954115ae3")

    $bodyLines = (
        "--$boundary",
        "Content-Disposition: form-data; name=`"zip`"$LF",
        $fileEnc,
        "--$boundary--$LF"
    ) -join $LF

    Invoke-RestMethod https://rink.hockeyapp.net/api/2/apps/upload -Method Post
    -ContentType "multipart/form-data; boundary=`"$boundary`""
    -Body $bodyLines -Headers $headers
